name: Changelog ğŸ“‹
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Print ğŸ“
    steps:
      - name: Checkout ğŸ“¥
        uses: actions/checkout@v6
      - name: Java â˜•ï¸
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Gradle ğŸ˜
        uses: gradle/actions/setup-gradle@v5
      - name: Changelog Print ğŸ–¨ï¸
        run: ./gradlew changelogPrint
