name: CI â™»ï¸
on:
  pull_request:
  push:
    branches: [main, release]
  workflow_dispatch:
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
jobs:
  sanity:
    name: Sanity ğŸ¦¢
    runs-on: ubuntu-latest
    env:
      buildcacheuser: ${{secrets.BUILDCACHE_USER}}
      buildcachepass: ${{secrets.BUILDCACHE_PASS}}
    steps:
      - name: Checkout ğŸ“¥
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Java Setup â˜•ï¸
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21
      - name: Gradle Setup ğŸ˜
        uses: gradle/actions/setup-gradle@v5
      - name: Spotless âœ¨
        run: ./gradlew spotlessCheck
      - name: Rewrite ğŸ­ï¸
        run: ./gradlew rewriteDryRun
      - name: Assemble Test Classes ğŸ—ï¸
        run: ./gradlew assemble testClasses
  build:
    needs: sanity
    name: Build ğŸ—ï¸
    strategy:
      fail-fast: false
      matrix:
        kind: [maven, gradle]
        jre: [17, 21, 24]
        os: [ubuntu-latest, windows-latest]
        include:
          - kind: npm
            jre: 17
            os: ubuntu-latest
          - kind: shfmt
            jre: 17
            os: ubuntu-latest
            shfmt-version: v3.8.0
          - kind: idea
            jre: 17
            os: ubuntu-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout ğŸ“¥
        uses: actions/checkout@v6
      - name: Java Setup â˜•ï¸ï¸
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{matrix.jre}}
      - name: Gradle Setup ğŸ˜
        uses: gradle/actions/setup-gradle@v5
      - name: Maven Plugin ğŸ—ï¸
        if: matrix.kind == 'maven'
        run: ./gradlew :plugin-maven:build -x spotlessCheck
      - name: Gradle Plugin ğŸ—ï¸
        if: matrix.kind == 'gradle'
        run: ./gradlew build -x spotlessCheck -PSPOTLESS_EXCLUDE_MAVEN=true
      - name: NPM Integration ğŸ§ª
        if: matrix.kind == 'npm'
        run: ./gradlew testNpm
      - name: Setup Go for shfmt ğŸ¦«
        if: matrix.kind == 'shfmt'
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
      - name: Install shfmt ğŸ”§
        if: matrix.kind == 'shfmt'
        run: go install mvdan.cc/sh/v3/cmd/shfmt@${{matrix.shfmt-version}}
      - name: shfmt Integration ğŸ§ª
        if: matrix.kind == 'shfmt'
        run: ./gradlew testShfmt
      - name: IDEA Integration ğŸ§ª
        if: matrix.kind == 'idea'
        run: |
          download_link=$(curl https://data.services.jetbrains.com/products/releases\?code\=IIC\&latest\=true\&type\=release | jq -r '.IIC[0].downloads.linux.link')
          curl --location "$download_link" -o idea.tar.gz
          tar -xf idea.tar.gz
          cd idea-IC*
          export PATH=${PATH}:$(pwd)/bin
          cd ..
          ./gradlew testIdea
      - name: Test Report ğŸ“Š
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          check_name: JUnit ${{matrix.kind}} ${{matrix.jre}} ${{matrix.os}}
          report_paths: '*/build/test-results/*/TEST-*.xml'
          check_retries: true
  complete:
    needs:
      - sanity
      - build
    name: Complete â˜‘ï¸
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check Job Results ğŸ”
        run: |
          results=$(tr -d '\n' <<< '${{toJSON(needs.*.result)}}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            echo "âŒ One or more required jobs failed."
            exit 1
          fi
          echo "âœ… All jobs successfully completed."
