# NEXUS_USER
# NEXUS_PASS64 (base64 NOTE: `base64` and `openssl base64` failed, had to use Java
#   byte[] data = "{{password}}".getBytes(StandardCharsets.UTF_8);
#   String encoded = new String(Base64.getEncoder().encode(data), StandardCharsets.UTF_8);
#   System.out.println(encoded);
# GPG_PASSPHRASE
# GPG_KEY64 (base64)
#   gpg --export-secret-keys --armor KEY_ID | openssl base64 | pbcopy
# GRADLE_KEY
# GRADLE_SECRET
name: Deploy ğŸ“¦
on:
  workflow_dispatch:
    inputs:
      to_publish:
        description: 'What to publish'
        required: true
        default: 'all'
        type: choice
        options:
          - plugin-gradle
          - plugin-maven
          - all
          - lib
jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Release ğŸ“¡
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      ORG_GRADLE_PROJECT_nexus_user: ${{secrets.NEXUS_USER}}
      ORG_GRADLE_PROJECT_nexus_pass64: ${{secrets.NEXUS_PASS64}}
      ORG_GRADLE_PROJECT_gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
      ORG_GRADLE_PROJECT_gpg_key64: ${{secrets.GPG_KEY64}}
    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v6
      - name: Setup Java â˜•ï¸
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle ğŸ˜
        uses: gradle/actions/setup-gradle@v5
      - name: Fetch Latest Main Branch ğŸ”„
        run: git fetch origin main
      - name: Publish All Components ğŸ“¦
        if: "${{github.event.inputs.to_publish == 'all'}}"
        run: |
          ./gradlew :changelogPush -Prelease=true --stacktrace --warning-mode all --no-configuration-cache
          ./gradlew :plugin-gradle:changelogPush -Prelease=true -Pgradle.publish.key=${{secrets.GRADLE_KEY}} -Pgradle.publish.secret=${{secrets.GRADLE_SECRET}} --stacktrace --warning-mode all --no-configuration-cache
          ./gradlew :plugin-maven:changelogPush -Prelease=true --stacktrace --warning-mode all --no-configuration-cache
      - name: Publish Gradle Plugin Only ğŸ“¦
        if: "${{github.event.inputs.to_publish == 'plugin-gradle'}}"
        run: ./gradlew :plugin-gradle:changelogPush -Prelease=true -Pgradle.publish.key=${{secrets.GRADLE_KEY}} -Pgradle.publish.secret=${{secrets.GRADLE_SECRET}} --stacktrace --warning-mode all --no-configuration-cache
      - name: Publish Maven Plugin Only ğŸ“¦
        if: "${{github.event.inputs.to_publish == 'plugin-maven'}}"
        run: ./gradlew :plugin-maven:changelogPush -Prelease=true --stacktrace --warning-mode all --no-configuration-cache
      - name: Publish Library Only ğŸ“¦
        if: "${{github.event.inputs.to_publish == 'lib'}}"
        run: ./gradlew :changelogPush -Prelease=true --stacktrace --warning-mode all --no-configuration-cache
